export const questions = [
    {
        question:"Care sunt organele mobile ale mecanismului motor?",
        answer:"pistonul, segmenţii, bolţul, biela, arborele cotit şi volantul",
        wrong_answer1:"blocul motor, cilindrii, chiulasa şi carterul",
        wrong_answer2:"roţile directoare şi cele tractoare",
        image_url:null,
    },
    {
        question:"Care sunt organele fixe ale mecanismului motor ?",
        answer:"blocul motor , cilindrii , chiulasa şi carterul",
        wrong_answer1:"pistonul , sgmenţii , bolţul , biela , arborele cotit şi volantul",
        wrong_answer2:"roţile directoare şi cele tractoare ",
        image_url:null,
    },
    {
        question:"Prezenţa calaminei pe suprafaţa bujiilor şi fumul albăstrui al eşapamentului indică:",
        answer:"mecanismul motor (grup piston-cilindru) este uzat",
        wrong_answer1:"rularea frecventă cu o viteză inferioară limitei legale",
        wrong_answer2:"folosirea unor bujii necorespunzătoare",
        image_url:null,
    },
    {
        question:"Ce rol are ambreiajul ?",
        answer:"realizează cuplarea progresivă şi decuplarea motorului de restul transmisiei",
        wrong_answer1:"asigură viteze diferite ale roţilor motoare la parcurgerea curbelor",
        wrong_answer2:"comandă mărirea turaţiei motorului, în funcţie de sarcina transportată",
        image_url:null,
    },
    {
        question:"Ce deprindere greşită a conducătorului auto determină frecvent defectarea ambreiajului?",
        answer:"aşteptarea la semafor având pedala de ambreiaj apăsată",
        wrong_answer1:"coborârea pantelor cu motorul oprit sau aducerea schimbătorului de viteze în punctul mort",
        wrong_answer2:"rularea cu jocuri mari la pedala de ambreiaj sau la mecanismul de direcţie",
        image_url:null,
    },
    {
        question:"Ce factor influenţează cel mai mult durata de serviciu a pneurilor?",
        answer:"presiunea",
        wrong_answer1:"temperatura mediului ambiant",
        wrong_answer2:"starea tehnică a frânei",
        image_url:null,
    },
    {
        question:"Uzura prematură a pneurilor din faţă se datorează, în primul rând",
        answer:"dereglării geometriei direcţiei",
        wrong_answer1:"circulaţiei frecvente cu viteză redusă",
        wrong_answer2:"fenomenul este specific autovehiculelor care au tracţiunea pe puntea din spate",
        image_url:null,
    },
    {
        question:"Când măsuraţi presiunea din pneuri?",
        answer:"înaintea plecării în cursă, când pneurile sunt reci",
        wrong_answer1:"după parcurgerea a cel puţin 400-500 km, când pneurile sunt calde",
        wrong_answer2:"doar atunci când observăm că autovehiculul este înclinat într-o parte",
        image_url:null,
    },
    {
        question:"Uzura pneurilor creşte foarte mult:",
        answer:"la demarări şi frânări intense, consecinţe ale unui stil agresiv de conducere",
        wrong_answer1:"atunci când se conduce preventiv-defensiv",
        wrong_answer2:"la circulaţia pe timp nefavorabil",
        image_url:null,
    },
    {
        question:"Când este indicat să verificaţi presiunea din anvelope?",
        answer:"de regulă, înainte de a porni la drum",
        wrong_answer1:"întotdeauna la 300 km",
        wrong_answer2:"numai pe timp de iarnă, când anvelopele sunt reci",
        image_url:null,
    },
    {
        question:"Cuvântul TUBBELESS, imprimat pe o anvelopă, semnifică ?",
        answer:"anvelopa poate funcţiona fără cameră de aer",
        wrong_answer1:"secţiunea pneului are formă tubulară",
        wrong_answer2:"anvelopa este destinată circulaţiei pe timp nefavorabil ",
        image_url:null,
    },
    {
        question:"Fumul de culoare neagră emis de eşapament indică:",
        answer:"un consum exagerat de combustibil",
        wrong_answer1:"defectarea supapelor de evacuare",
        wrong_answer2:"un consum exagerat de ulei",
        image_url:null,
    },
    {
        question:"Care sunt factorii care fac ca motorul Diesel al unui autoturism să emită fum excesiv?",
        answer:"defecţiuni la instalaţia de injecţie",
        wrong_answer1:"buşonul rezervorului închis la maximum",
        wrong_answer2:"lipsa combustibilului",
        image_url:null,
    },
    {
        question:"Criteriul de alegere a benzinei pentru motoarele cu aprindere prin scânteie îl constituie:",
        answer:"cifra octanică (CO);",
        wrong_answer1:"culoarea şi consistenţa",
        wrong_answer2:"cifra catanică (CC)",
        image_url:null,
    },
    {
        question:"Ce reprezintă simbolurile EURO I, EURO II, EURO III şi EURO IV?",
        answer:"standardele de poluare din Uniunea Europeană",
        wrong_answer1:"caracteristicile tehnice de provenienţă a unor vehicule din Uniunea Europeană",
        wrong_answer2:"încadrarea autovehiculelor în diferite norme de consum",
        image_url:null,
    },
    {
        question:"Temperatura lichidului de răcire care asigură performanţa maximă şi uzura minimă a motorului este cuprinsă în intervalul:",
        answer:"90-95 grade C",
        wrong_answer1:"100-120 grade C",
        wrong_answer2:"60-70 grade C",
        image_url:null,
    },
    {
        question:"Termostatul aparţine instalaţiei de:",
        answer:"răcire",
        wrong_answer1:"ungere",
        wrong_answer2:"alimentare",
        image_url:null,
    },
    {
        question:"Cea mai frecventă defecţiune a instalaţiei de răcire a motorului este:",
        answer:"slăbirea sau ruperea curelei de antrenare a ventilatorului şi a pompei de apă",
        wrong_answer1:"înfundarea prizei de aer care alimentează ventilatorul",
        wrong_answer2:"patinarea ambreiajului",
        image_url:null,
    },
    {
        question:"Ce măsuri de precauţie trebuie să luaţi la utilizarea soluţiei antigel?",
        answer:"se va evita contactul cu aceasta, deoarece este toxică",
        wrong_answer1:"nicio măsură, întrucât lichidul respectiv nu este nociv",
        wrong_answer2:"nu se va combina cu apa, deoarece degajă multă căldură",
        image_url:null,
    },
    {
        question:"Circulaţia frecventă cu termostatul defect şi, implicit, cu o temperatură a lichidului de răcire sub 60 grade Celsius conduce la:",
        answer:"creşterea consumului de combustibil",
        wrong_answer1:"imposibilitatea încălzirii habitaclului",
        wrong_answer2:"blocarea pompei de apă",
        image_url:null,
    },

]