export const questions = [
    {
        question:"Când se poate face radierea din evidenţă a unui vehicul, la cererea proprietarului?",
        answer:"când proprietarul face dovada dezmembrării, casării sau predării vehiculului la unităţi specializate, în vederea dezmembrării",
        wrong_answer1:"la schimbarea domiciliului ori a sediului unităţii deţinătoare",
        wrong_answer2:"la schimbarea oricăror date referitoare la identificarea vehiculului respectiv",
        image_url:null,
    },
    {
        question:"În ce condiţii pot circula pe drumurile publice autovehiculele şi remorcile?",
        answer:"când sunt în bună stare de funcţionare şi îndeplinesc condiţiile tehnice stabilite prin lege",
        wrong_answer1:"când au un aspect civilizat",
        wrong_answer2:"când nu depăşesc greutatea şi gabaritul înscrise în certificatul de înmatriculare",
        image_url:null,
    },
    {
        question:"Care autovehicule trebuie să-şi refacă inspecţia tehnică înainte de termen?",
        answer:"autovehiculele cu sistemele de frânare şi de direcţie grav avariate",
        wrong_answer1:"autovehiculele mai vechi de 10 ani",
        wrong_answer2:"autovehiculele cu inscripţia „ŞCOALĂ“",
        image_url:null,
    },
    {
        question:"În ce situaţie se interzice circulaţia autovehiculelor pe drumurile publice?",
        answer:"când plăcuţele cu numărul de înmatriculare sunt neconforme cu standardul",
        wrong_answer1:"când parbrizul prezintă fisuri",
        wrong_answer2:"când acestea au montate dispozitive de detectare a prezenţei aparatelor radar",
        image_url:null,
    },
    {
        question:"Inspecţia tehnică periodică a autovehiculelor şi a remorcilor trebuie efectuată:",
        answer:"periodic, conform legii",
        wrong_answer1:"anual, la orice service auto",
        wrong_answer2:"la cel mult doi ani, la o staţie de inspecţie tehnică autorizată",
        image_url:null,
    },
    {
        question:"Este permisă montarea, de către deţinătorul unui autovehicul, a unui alt avertizor sonor în afara celui omologat de către autoritatea competentă?",
        answer:"nu.",
        wrong_answer1:"da, cu condiţia ca acesta să nu fie deranjant din punct de vedere sonor",
        wrong_answer2:"Regulamentul nu prevede nimic în acest sens",
        image_url:null,
    },
    {
        question:"Sunteţi obligat să aveţi în autovehicul",
        answer:"o trusă medicală de prim ajutor, două triunghiuri reflectorizante şi un stingător de incendiu omologat",
        wrong_answer1:"numai trusa medicală de prim ajutor",
        wrong_answer2:"numai trusa medicală de prim ajutor şi triunghiuri reflectorizante",
        image_url:null,
    },
    {
        question:"Instalaţiile de semnalizare şi iluminare ale unui autovehicul trebuie:",
        answer:"să corespundă condiţiilor tehnice impuse şi să fie omologate de către autoritatea competentă",
        wrong_answer1:"să funcţioneze doar pe timp de noapte",
        wrong_answer2:"să nu fie folosite în mediul urban",
        image_url:null,
    },
    {
        question:"Cum trebuie să aveţi reglat sistemul de lumini pentru circulaţia pe timp de noapte?",
        answer:"astfel încât să vedeţi şi să fiţi văzut, fără a-i stânjeni pe ceilalţi participanţi la trafic",
        wrong_answer1:"să vedeţi cât mai bine în faţă, indiferent dacă sunt deranjaţi ceilalţi participanţi la trafic cu care vă întersectaţi",
        wrong_answer2:"să asiguraţi, cel puţin, funcţionarea farului din partea dreaptă",
        image_url:null,
    },
    {
        question:"La cererea poliţistului rutier, împreună cu reprezentantul autorităţilor abilitate, conducătorul auto este obligat:",
        answer:"să permită controlul stării tehnice a vehiculului, precum şi al bunurilor transportate",
        wrong_answer1:"să-l transporte la unitatea de poliţie",
        wrong_answer2:"să prezinte documentele de călătorie",
        image_url:null,
    },
    {
        question:"Conducătorii de autovehicule pot folosi mijloace proprii de detectare a dispozitivelor de măsurare a vitezei?",
        answer:"da",
        wrong_answer1:"acest aspect nu este stabilit legal",
        wrong_answer2:"nu",
        image_url:null,
    },
    {
        question:"Ce obligaţii are conducătorul auto atunci când un poliţist îi solicită documentele?",
        answer:"să înmâneze documentele prevăzute de lege",
        wrong_answer1:"să prezinte certificatul de înmatriculare şi cartea de identitate a vehiculului",
        wrong_answer2:"să prezinte documentele personale",
        image_url:null,
    },
    {
        question:"Ce obligaţii are conducătorul unui autovehicul, dacă pe drumul pe care circulă observă evenimente de natură a pune în pericol siguranţa circulaţiei?",
        answer:"să sesizeze cea mai apropiată unitate de poliţie în legătură cu obstacolele sau situaţiile care pun în pericol siguranţa circulaţiei",
        wrong_answer1:"să emită semnale acustice ori de câte ori se întâlneşte cu un alt vehicul circulând din sens opus",
        wrong_answer2:"să semnalizeze participanţii la trafic care circulă din sens opus, schimbând alternativ lumina de drum cu lumina de întâlnire",
        image_url:null,
    },
    {
        question:"Este interzis ca autovehiculele să fie echipate cu",
        answer:"dispozitive antiradar",
        wrong_answer1:"sisteme de navigaţie",
        wrong_answer2:"sisteme sonor antifurt",
        image_url:null,
    },
    {
        question:"Ce obligaţii aveţi dacă sunteţi oprit regulamentar de către un poliţist rutier?",
        answer:"să rămâneţi în vehicul, cu mâinile pe volan, respectând indicaţiile poliţistului;",
        wrong_answer1:"să coborâţi din vehicul pentru a prezenta permisul de conducere",
        wrong_answer2:"să coborâţi din vehicul pentru a lua la cunoştinţă abaterea comisă",
        image_url:null,
    },
    {
        question:"Puteţi schimba poziţia autovehiculului, dacă acesta a fost implicat într-un accident din care a rezultat moartea sau vătămarea integrităţii corporale ori a sănătăţii unor persoane?",
        answer:"da, cu încuviinţarea poliţiei, care cercetează accidentul",
        wrong_answer1:"da, dacă persoana vătămată se poate deplasa singură",
        wrong_answer2:"nu, până la sosirea ambulanţei",
        image_url:null,
    },
    {
        question:"Puteţi schimba poziţia autovehiculului, dacă sunteţi implicat într-un accident de circulaţie?",
        answer:"da, dacă accidentul s-a soldat numai cu avarii",
        wrong_answer1:"da, după ce aţi anunţat poliţia",
        wrong_answer2:"da, după ce aţi acordat primul ajutor victimelor",
        image_url:null,
    },
    {
        question:"Ce trebuie să faceţi imediat după un accident cu un animal sălbatic?",
        answer:"opriţi, aprindeţi luminile de avarie şi asiguraţi locul accidentului",
        wrong_answer1:"înştiinţaţi societăţile de protecţie a animalelor",
        wrong_answer2:"luaţi vânatul acasă şi comunicaţi societăţii de asigurare daunele suferite de autoturism",
        image_url:null,
    },
    {
        question:"Unde trebuie să se deplaseze conducătorii de autovehicule angajaţi într-un accident de circulaţie, în urma căruia au rezultat pagube materiale, pentru a obţine actul de constatare?",
        answer:"la cea mai apropiată unitate de poliţie competentă, în maximum 24 de ore",
        wrong_answer1:"la serviciul judeţean de poliţie rutieră",
        wrong_answer2:"la unitatea de poliţie în raza căreia domiciliază",
        image_url:null,
    },
    

]