export const questions = [
    {
        question:"Ce trebuie să aveţi în vedere la scoaterea persoanelor accidentate din autovehicul?",
        answer:"să nu se agraveze leziunile",
        wrong_answer1:"ca operaţiunea să se desfăşoare rapid şi fără să provoace alte traumatisme",
        wrong_answer2:"să nu se îndepărteze indiciile care ar putea ajuta la explicarea modului în care s-a produs accidentul",
        image_url:null,
    },
    {
        question:"Ce măsuri se iau în cazul accidentării foarte grave a unei persoane, într-un accident de circulaţie?",
        answer:"acordarea primului ajutor, până la sosirea ambulanţei",
        wrong_answer1:"transportul imediat până la prima localitate şi anunţarea ambulanţei",
        wrong_answer2:"transportul imediat la cea mai apropiată unitate sanitară, cu orice mijloc de transport posibil",
        image_url:null,
    },
    {
        question:"Cum trebuie să procedeze conducătorul unui autovehicul dacă i-a fost prescris un tratament medicamentos?",
        answer:"să nu îşi administreze medicamentele înainte de a se urca la volan",
        wrong_answer1:"să se asigure că administrarea acestuia nu-i va afecta capacitatea de a conduce",
        wrong_answer2:"să se informeze care este doza minimă care poate fi administrată pe perioada cât se află la volan",
        image_url:null,
    },
    {
        question:". În funcţie de starea accidentatului, măsurile de prim ajutor se vor lua în următoarea ordine",
        answer:"respiraţia artificială, masajul cardiac, oprirea hemoragiei, pansarea rănilor, imobilizarea fracturilor",
        wrong_answer1:"oprirea hemoragiei, pansarea rănilor, imobilizarea fracturilor, respiraţia artificială, masajul cardiac",
        wrong_answer2:"imobilizarea fracturilor, pansarea rănilor, respiraţia artificială, masajul cardiac, oprirea hemoragiei",
        image_url:null,
    },
    {
        question:"Cum trebuie scoase dintr-un autovehicul persoanele rănite?",
        answer:"prin ridicare",
        wrong_answer1:"prin tragere",
        wrong_answer2:"prin împingere",
        image_url:null,
    },
    {
        question:"În cazul unui accident de circulaţie cu victime şi cu deformarea accentuată a caroseriei sau a blocării uşilor, ocupanţii vehiculelor pot fi imobilizaţi. Cum se acţionează în astfel de situaţii?",
        answer:"se apelează la serviciile specializate ale unităţilor de pompieri, care intervin cu utilaje de descarcerare",
        wrong_answer1:"se extrag victimele rapid şi ferm",
        wrong_answer2:"se cere ajutorul celor din jur şi se scot rapid victimele dintre fiarele contorsionate",
        image_url:null,
    },
    {
        question:"În cazul unui accident cu victime şi cu deformarea accentuată a caroseriei, procedaţi la:",
        answer:"victimele conştiente sunt sfătuite să nu se mişte, iar degajarea acestora trebuie să se realizeze cât mai repede şi numai de către echipaje specializate",
        wrong_answer1:"degajarea victimelor trebuie să se realizeze cât mai repede, prin orice mijloace",
        wrong_answer2:"se administrează calmante victimelor care sunt conştiente",
        image_url:null,
    },
    {
        question:"Ce trebuie să aibă în vedere prima intervenţie, la faţa locului, pentru salvarea victimei?",
        answer:"degajarea căilor respiratorii şi asigurarea funcţiei respiratorii",
        wrong_answer1:"spălarea rănilor vizibile;",
        wrong_answer2:"igienizarea şi pansarea rănilor",
        image_url:null,
    },
    {
        question:"Când constataţi că aveţi anumite probleme cu vederea, trebuie:",
        answer:"să evitaţi conducerea autovehiculului până când sunteţi consultat de medicul specialist, urmând să vă conformaţi sfaturilor acestuia",
        wrong_answer1:"să vă cumpăraţi ochelari de vedere cu caracteristici superioare",
        wrong_answer2:"să conduceţi folosind lumina de drum chiar şi în localităţi sau când din sens opus se apropie alte vehicule",
        image_url:null,
    },
    {
        question:"Este obligatorie dotarea autovehiculelor cu trusă medicală de prim ajutor?",
        answer:"da, pentru toate autovehiculele care circulă pe drumurile publice",
        wrong_answer1:"nu, fiind doar o recomandare legală",
        wrong_answer2:"da, numai la autovehiculele cu o greutate mai mare de 3,5 t",
        image_url:null,
    },
    {
        question:"Gravitatea unei hemoragii se apreciază în funcţie de:",
        answer:"cantitatea sângelui pierdut",
        wrong_answer1:"culoarea sângelui scurs",
        wrong_answer2:"fluiditatea sângelui scurs",
        image_url:null,
    },
    {
        question:"Cum se acordă primul ajutor în cazul plăgilor tăiate?",
        answer:"acoperiţi rana şi opriţi sângerarea, apoi transportaţi rănitul la medic sau la spital",
        wrong_answer1:"opriţi sângerarea prin coaserea plăgii",
        wrong_answer2:"transportaţi rănitul la medic, fără să faceţi nimic altceva",
        image_url:null,
    },
    {
        question:"În rănile cu hemoragie se va avea în vedere, în faza iniţială:",
        answer:"oprirea hemoragiei",
        wrong_answer1:"pansarea rănii",
        wrong_answer2:"curăţarea şi pansarea rănii",
        image_url:null,
    },
    {
        question:"În cazul unui accidentat cu hemoragie masivă, acţionaţi astfel",
        answer:"aşezaţi persoana pe spate, cu picioarele ridicate, imobilizaţi eventualele fracturi, nu îi daţi să bea lichide şi o protejaţi contra frigului",
        wrong_answer1:"aşezaţi persoana pe abdomen şi îi daţi să bea cât mai multe lichide",
        wrong_answer2:"aşezaţi persoana pe un scaun în poziţia şezând şi vorbiţi cu ea",
        image_url:null,
    },
    {
        question:"Accidentatul cu hemoragie externă trebuie aşezat:",
        answer:"în aşa fel încât rana sângerândă să fie mai sus decât nivelul corpului",
        wrong_answer1:"nu are importanţă dacă rana este situată mai sus sau mai jos decât planul corpului",
        wrong_answer2:"în aşa fel încât rana care sângerează să fie mai jos decât planul corpului",
        image_url:null,
    },
    {
        question:"O hemoragie produsă la unul dintre membrele unei persoane rănite se va opri prin:",
        answer:"acţiunea compresivă asupra vasului lezat sau aplicarea garoului",
        wrong_answer1:"dezinfectarea rănii, pansarea şi aplicarea atelelor",
        wrong_answer2:"ridicarea membrului accidentat în poziţie verticală",
        image_url:null,
    },
    {
        question:"Bandajele se folosesc",
        answer:"pentru acoperirea şi pentru susţinerea rănilor, precum şi pentru oprirea hemoragiilor",
        wrong_answer1:"pentru susţinerea părţilor lezate",
        wrong_answer2:"pentru imobilizarea fracturilor",
        image_url:null,
    },
    {
        question:"Victima care a pierdut mult sânge trebuie să fie aşezată",
        answer:"cu picioarele situate mai sus decât nivelul corpului",
        wrong_answer1:"cu faţa în sus",
        wrong_answer2:"cu faţa în jos",
        image_url:null,
    },
    {
        question:"Oprirea hemoragiei se face prin legarea strânsă a braţului",
        answer:"deasupra rănii",
        wrong_answer1:"în dreptul rănii",
        wrong_answer2:"sub rană",
        image_url:null,
    },
    {
        question:"Ce trebuie să conţină biletul care se prinde lângă garoul aplicat unei persoane rănite?",
        answer:"ora şi minutul aplicării garoului",
        wrong_answer1:"poziţia în care a fost găsită victima",
        wrong_answer2:"datele de stare civilă ale persoanei",
        image_url:null,
    },
    {
        question:"O funcţie a bandajului este",
        answer:"de a opri hemoragia",
        wrong_answer1:"de a preveni murdărirea hainelor",
        wrong_answer2:"de a acoperi aspectul neplăcut al rănii",
        image_url:null,
    },

]