export const questions = [
    {
        question:"Conducătorii de vehicule trebuie să respecte regulile de circulaţie, generale şi particulare, în următoarea ordine:",
        answer:"semnalele, indicaţiile şi dispoziţiile poliţistului rutier; semnalele speciale de avertizare, luminoase sau sonore, ale autovehiculelor cu regim de circulaţie prioritară; semnalizarea temporară",
        wrong_answer1:"semnalele, indicaţiile şi dispoziţiile poliţistului rutier; semnalizarea temporară; semnalele speciale de avertizare, luminoase sau sonore, ale autovehiculelor cu regim de circulaţie prioritară",
        wrong_answer2:". semnalele speciale de avertizare, luminoase sau sonore, ale autovehiculelor cu regim de circulaţie prioritară; semnalele, indicaţiile şi dispoziţiile poliţistului rutier; semnalizarea temporară",
        image_url:null,
    },
    {
        question:"Care dintre tipurile de semnalizare de mai jos vor fi respectate cu prioritate?",
        answer:"semnalele şi indicaţiile poliţistului",
        wrong_answer1:"semnalele luminoase",
        wrong_answer2:"semnalizarea temporară, care modifică regimul normal de desfăşurare a circulaţiei",
        image_url:null,
    },
    {
        question:". Dacă poliţistul se află în intersecţie cu faţa către conducătorul autovehiculului şi îi adresează acestuia un alt semnal decât poziţia sa, care înseamnă Oprire ,conducătorul trebuie:",
        answer:"să respecte semnalul poliţistului;",
        wrong_answer1:"să continue mersul, deoarece semnele poliţistului sunt contradictorii",
        wrong_answer2:"să oprească şi să aştepte semnalul pentru continuarea deplasării",
        image_url:null,
    },
    {
        question:"Cum procedaţi în situaţia în care semnalul roşu al semaforului este în funcţiune, iar poliţistul vă adresează semnalul de a trece?",
        answer:"respectaţi semnalul poliţistului",
        wrong_answer1:"atrageţi atenţia poliţistului că există neconcordanţă între semnalul său şi cel al semaforului",
        wrong_answer2:"aşteptaţi apariţia semnalului de culoare verde, care vă permite să circulaţi cu autovehiculul prin intersecţie",
        image_url:null,
    },
    {
        question:"La semnalul poliţistului situat într-o intersecţie, cu braţul ridicat vertical, aveţi obligaţia:",
        answer:"să opriţi, indiferent din ce direcţie circulaţi",
        wrong_answer1:"să reduceţi viteza",
        wrong_answer2:"să circulaţi cu prudenţă maximă",
        image_url:null,
    },
    {
        question:"Braţul drept, întins orizontal, al poliţistului indică Oprire pentru",
        answer:"vehiculele şi pietonii care vin din spate",
        wrong_answer1:"vehiculele şi pietonii care vin din faţă",
        wrong_answer2:"vehiculele şi pietonii care vin din faţă şi din spate",
        image_url:null,
    },
    {
        question:"În situaţia în care poliţistul se află cu faţa la un autovehicul care se apropie, având braţul drept întins orizontal, conducătorul auto trebuie  ",
        answer:"să continue deplasarea, deoarece semnalul nu i se adresează",
        wrong_answer1:"să oprească, deoarece semnalul i se adresează",
        wrong_answer2:"să schimbe direcţia de mers spre stânga",
        image_url:null,
    },
    {
        question:"Braţul stâng, întins orizontal, al poliţistului semnifică oprire pentru",
        answer:". vehiculele care vin din faţă",
        wrong_answer1:"vehiculele care vin din spate",
        wrong_answer2:"vehiculele care vin din faţă şi din spate",
        image_url:null,
    },
    {
        question:"Când poliţistul se află cu spatele la autovehiculul care se apropie şi cu braţul stâng întins orizontal, conducătorul acestuia trebuie  ",
        answer:". să continue deplasarea, deoarece semnalul de oprire nu i se adresează",
        wrong_answer1:"să schimbe direcţia de mers spre stânga",
        wrong_answer2:"să oprească, deoarece semnalul i se adresează",
        image_url:null,
    },
    {
        question:"La semnalul poliţistului având braţul stâng întins orizontal, orientat cu faţa către autovehiculul care se apropie, conducătorul auto trebuie ",
        answer:"să oprească imediat",
        wrong_answer1:"să reducă viteza",
        wrong_answer2:"să continue deplasarea",
        image_url:null,
    },
    {
        question:"Braţele întinse orizontal, ale poliţistului care dirijează circulaţia, semnifică",
        answer:"oprire pentru toţi participanţii la trafic care, indiferent de sensul lor de mers, circulă din direcţia sau direcţiile intersectate de braţele întinse ale acestuia  ",
        wrong_answer1:"oprire pentru toţi participanţii la trafic care circulă numai din spatele acestuia",
        wrong_answer2:"oprire pentru toţi participanţii la trafic care circulă numai din faţa acestuia",
        image_url:null,
    },
    {
        question:". Ce semnificaţie are, după coborârea braţelor, poziţia corpului unui poliţist care dirijează circulaţia, pentru participanţii la trafic care circulă din faţa şi spatele său?",
        answer:"Oprire",
        wrong_answer1:"nicio semnificaţie",
        wrong_answer2:"permisiunea de a circula",
        image_url:null,
    },
    {
        question:"Scoaterea, pe partea laterală din dreapta, a bastonului reflectorizant de către poliţistul care însoţeşte o coloană oficială de autovehicule obligă conducătorii care  circulă în spatele acesteia: ",
        answer:". să oprească cât mai aproape de marginea drumului, iar acolo unde este posibil, să scoată vehiculul în afara părţii carosabile;",
        wrong_answer1:"să reducă imediat viteza şi să circule cât mai aproape de marginea drumului",
        wrong_answer2:"să reducă viteza şi să iasă în afara drumului imediat ce este posibil, prin viraj la dreapta.",
        image_url:null,
    },
    {
        question:"Semnalul poliţistului rutier aflat într-un autovehicul al poliţiei, efectuat cu braţul, cu sau fără baston reflectorizant, scos pe partea laterală dreaptă a vehiculului, semnifică:",
        answer:"oprire pentru conducătorii vehiculelor care circulă în spatele autovehiculului poliţiei",
        wrong_answer1:"reducerea vitezei de către cei care circulă în spatele autovehiculului poliţiei",
        wrong_answer2:"semnalul se adresează celor care circulă din sens opus",
        image_url:null,
    },
    {
        question:"Ce obligaţii revin conducătorilor de vehicule la trecerea autovehiculelor cu regim de circulaţie prioritară, care au în funcţiune mijloacele speciale de avertizare luminoasă de culoare roşie şi pe cele de avertizare sonoră:",
        answer:"să oprească imediat pe acostament sau, în lipsa acestuia, cât mai aproape de marginea drumului sau de bordura trotuarului, în sensul de deplasare",
        wrong_answer1:"să reducă viteza şi să circule cât mai aproape de marginea drumului în sensul de deplasare",
        wrong_answer2:"să scoată vehiculul în afara drumului, indiferent prin ce mijloace",
        image_url:null,
    },
    {
        question:"Ce obligaţii aveţi dacă întâlniţi un vehicul cu semnalele speciale de avertizare luminoase de culoare albastră în funcţiune?",
        answer:"acordaţi prioritate vehiculului de mai sus",
        wrong_answer1:"opriţi cât mai aproape de marginea drumului",
        wrong_answer2:". nicio obligaţie, deoarece semnalul albastru se adresează coloanelor în mişcare",
        image_url:null,
    },
    {
        question:"Cum trebuie să procedeze conducătorul de autovehicul atunci când, într-o intersecţie, întâlneşte un poliţist orientat cu faţa spre el, care îi face semn să-şi continue deplasarea?",
        answer:"se conformează semnalului poliţistului",
        wrong_answer1:"fiind un semnal în afara Regulamentului, opreşte şi aşteaptă revenirea la o poziţie care să-i permită continuarea drumului",
        wrong_answer2:"opreşte până când poliţistul îşi schimbă poziţia",
        image_url:null,
    },
    {
        question:"Ce obligaţii revin conducătorilor de vehicule la trecerea autovehiculelor cu regim de circulaţie prioritară, care au în funcţiune mijloacele speciale de avertizare luminoasă de culoare albastră şi pe cele de avertizare sonoră?",
        answer:". să reducă viteza, să circule cât mai aproape de marginea drumului în sensul de deplasare şi să acorde prioritate de trecere;",
        wrong_answer1:". să mărească viteza pentru a nu incomoda circulaţia",
        wrong_answer2:". să oprească imediat, pe acostament sau, în lipsa acestuia, cât mai aproape de marginea drumului sau de bordura trotuarului, în sensul de deplasare",
        image_url:null,
    },
    {
        question:"Ce obligaţii aveţi dacă întâlniţi un vehicul care semnalizează cu luminile speciale de avertizare de culoare albastră şi semnalele sonore?",
        answer:"reduceţi viteza, circulaţi cât mai aproape de bordură sau acostament şi acordaţi prioritate vehiculului respectiv",
        wrong_answer1:"nicio obligaţie, deoarece semnalul albastru se adresează coloanelor în mişcare",
        wrong_answer2:"opriţi cât mai aproape de marginea drumului",
        image_url:null,
    },
    {
        question:"Care autovehicule pot fi echipate cu lumini speciale de avertizare de culoare albastră?",
        answer:"vehiculele aparţinând poliţiei, jandarmeriei şi poliţiei de frontieră",
        wrong_answer1:"legea nu prevede",
        wrong_answer2:"orice autovehicul pentru care se obţine aprobarea poliţiei rutiere",
        image_url:null,
    },
]