export const questions = [
    {
        question:"Pe străzile cu sens unic este interzis:",
        answer:"să întoarceţi autovehiculul",
        wrong_answer1:"să viraţi la stânga sau la dreapta",
        wrong_answer2:"să manevraţi înapoi autovehiculul",
        image_url:null,
    },
    {
        question:"Unde vă este permisă staţionarea pe partea stângă în direcţia de mers?",
        answer:"pe străzile cu sens unic",
        wrong_answer1:"în nicio situaţie",
        wrong_answer2:"pe şoselele cu bandă laterală consolidată",
        image_url:null,
    },
    {
        question:"Precizaţi în care situaţie vehiculele enumerate mai jos au prioritate de trecere:",
        answer:". vehiculele aflate în sensul giratoriu, faţă de cele care se pregătesc să intre în sensul giratoriu",
        wrong_answer1:"autovehiculele din serviciile regulate de transport public, care se pun în mişcare din staţie",
        wrong_answer2:"vehiculele care execută manevra de întoarcere",
        image_url:null,
    },
    {
        question:"Ce obligaţii are conducătorul de vehicul care intenţionează să intre pe prima stradă la dreapta, într-o intersecţie cu sens giratoriu?",
        answer:"semnalizează intenţia de a executa manevra, se asigură, se angajează cât mai aproape de marginea din dreapta, apoi intră pe strada respectivă",
        wrong_answer1:"ocoleşte sensul giratoriu, apoi schimbă direcţia de mers spre dreapta",
        wrong_answer2:"opreşte autovehiculul, se asigură şi execută schimbarea direcţiei de mers spre dreapta",
        image_url:null,
    },
    {
        question:"Dacă circulaţi într-o intersecţie cu sens giratoriu, acordaţi prioritate",
        answer:"niciunui vehicul",
        wrong_answer1:"vehiculelor care urmează să intre în intersecţie",
        wrong_answer2:"autobuzelor şi troleibuzelor",
        image_url:null,
    },
    {
        question:"Care sunt vehiculele care au prioritate în sensul giratoriu?",
        answer:"toate vehiculele care au pătruns în sensul giratoriu, faţă de cele care urmează să pătrundă",
        wrong_answer1:"toate autovehiculele care vin din faţă",
        wrong_answer2:"toate vehiculele care vin din dreapta",
        image_url:null,
    },
    {
        question:"Într-o intersecţie unde circulaţia se desfăşoară în sens giratoriu, conducătorilor auto le este interzis:",
        answer:"să oprească autovehiculele, în afara situaţiilor impuse de trafic",
        wrong_answer1:"să reducă viteza, întrucât se creează pericolul de blocare",
        wrong_answer2:"să întoarceţi, prin ocolirea sensului giratoriu",
        image_url:null,
    },
    {
        question:"Cum veţi parca regulamentar într-o piaţă cu sens giratoriu?",
        answer:"în acest loc nu este permisă parcarea",
        wrong_answer1:"paralel cu bordura trotuarului şi cât mai aproape de aceasta",
        wrong_answer2:"parţial pe trotuar",
        image_url:null,
    },
    {
        question:"Schimbarea direcţiei de mers la dreapta sau la stânga nu este permisă la întâlnirea:",
        answer:"indicatorului 2",
        wrong_answer1:"indicatorului 1",
        wrong_answer2:"ambelor indicatoare",
        image_url:"https://i.imgur.com/BaErvco.png",
    },
    {
        question:"Care este traseul de urmat pentru autoturismul din imagine?",
        answer:"oricare dintre cele două, dacă respectă toate prevederile legii",
        wrong_answer1:"traseul 1",
        wrong_answer2:"traseul 2",
        image_url:"https://i.imgur.com/gasRNCn.png",
    },
    {
        question:"Aţi selectat corect banda de circulaţie pentru a vira la stânga în intersecţia care urmează?",
        answer:"da",
        wrong_answer1:"nu",
        wrong_answer2:"sunteţi obligat să circulaţi numai înainte",
        image_url:"https://i.imgur.com/sjkBbXH.png",
    },
    {
        question:"Ce interdicţie aveţi în această situaţie?",
        answer:"să opriţi autovehiculul",
        wrong_answer1:"să acordaţi prioritate vehiculelor care intră în intersecţie",
        wrong_answer2:"să circulaţi cu o viteză mai mică de 30 km pe oră",
        image_url:"https://i.imgur.com/30fEqVg.png",
    },
    {
        question:"Care dintre autoturismele din imagine circulă corect în intersecţie?",
        answer:"toate cele patru autoturisme",
        wrong_answer1:"autoturismul mov şi cel roşu",
        wrong_answer2:"autoturismul albastru şi cel roşu",
        image_url:"https://i.imgur.com/5frfUQu.png",
    },
    {
        question:"În această situaţie, intenţionaţi să viraţi pe prima stradă la dreapta. Ce obligaţii aveţi?",
        answer:"Semnalizaţi intenţia de a executa manevra, vă asiguraţi,vă angajaţi cât mai aproape de marginea din dreapta, apoi viraţi la dreapta.",
        wrong_answer1:". opriţi, vă asiguraţi, apoi schimbaţi direcţia de mers spre dreapta",
        wrong_answer2:"ocoliţi sensul giratoriu, apoi schimbaţi direcţia de mers spre dreapta",
        image_url:"https://i.imgur.com/NpUlQY4.png",
    },
    {
        question:"Cum trebuie să procedaţi la întâlnirea indicatorului?",
        answer:"acordaţi prioritate vehiculelor care circulă în interiorul intersecţiei",
        wrong_answer1:"ocoliţi centrul intersecţiei prin stânga",
        wrong_answer2:"circulaţi cu o viteză maximă de 40 km/h",
        image_url:"https://i.imgur.com/jaH5S47.png",
    },
    {
        question:"Care autoturisme s-au încadrat corect pentru a traversa intersecţia prezentată?",
        answer:"toate",
        wrong_answer1:"autoturismul verde şi cel roşu",
        wrong_answer2:"autoturismul albastru şi cel galben",
        image_url:"https://i.imgur.com/6PbdUov.png",
    },
    {
        question:"Care dintre autovehiculele din imagine au prioritate de trecere?",
        answer:"motocicleta şi autocamionul",
        wrong_answer1:"autobuzul şi motocicleta",
        wrong_answer2:"autobuzul şi autoturismul",
        image_url:"https://i.imgur.com/vIZb6cw.png",
    },
    {
        question:"Care este traseul optim pentru a întoarce în intersecţia prezentată?",
        answer:"traseul 2",
        wrong_answer1:"traseul 1",
        wrong_answer2:"traseul 3",
        image_url:"https://i.imgur.com/qVkpj0t.png",
    },
    {
        question:"Care este traseul recomandat pentru a vira la stânga? ",
        answer:"traseul 2",
        wrong_answer1:"traseul 1",
        wrong_answer2:"virajul la stânga este interzis",
        image_url:"https://i.imgur.com/UITm0tT.png",
    },
    {
        question:"Ce obligaţii revin conducătorilor la întâlnirea indicatorului?",
        answer:"să acorde prioritate vehiculelor care circulă în intersecţie",
        wrong_answer1:"să ocolească centrul intersecţiei şi să circule cât mai aproape de marginea străzii",
        wrong_answer2:"să acorde prioritate de dreapta",
        image_url:"https://i.imgur.com/q11mTnt.png",
    }

]