export const questions = [
    {
        question:"Neacordarea priorităţii înseamnă:",
        answer:"obligarea celor care au prioritate de trecere de a-şi modifica brusc direcţia sau viteza de deplasare ori să oprească",
        wrong_answer1:"nerespectarea semnificaţiei semnalizării rutiere de obligare sau de avertizare",
        wrong_answer2:"nerespectarea dispoziţiilor legale privind asigurarea şi semnalizarea în intersecţii",
        image_url:null,
    },
    {
        question:"Ce regulă de prioritate se aplică într-o intersecţie nedirijată din afara localităţii?",
        answer:"prioritatea de dreapta",
        wrong_answer1:"prioritatea vehiculului cu regim superior de viteză",
        wrong_answer2:"prioritatea drumului principal",
        image_url:null,
    },
    {
        question:"Cum veţi proceda pentru a traversa intersecţia dacă întâlniţi indicatorul Cedează trecerea?",
        answer:"reduceţi viteza, vă asiguraţi, iar dacă pe drumul transversal circulă în acel moment alte vehicule, opriţi pentru a le acorda prioritate de trecere",
        wrong_answer1:"reduceţi viteza numai dacă se apropie vreun autovehicul",
        wrong_answer2:"reduceţi viteza şi vă asiguraţi, pentru a fi în măsură să acordaţi prioritate de trecere vehiculelor care circulă din partea dreaptă",
        image_url:null,
    },
    {
        question:"Cum procedează conducătorul de autovehicul la întâlnirea indicatorului Oprire?",
        answer:"opreşte unde are o bună vizibilitate pentru a se asigura şi îşi continuă deplasarea, dacă pe drumul transversal nu circulă alte vehicule",
        wrong_answer1:"reduce viteza, se asigură, după care intră în intersecţie",
        wrong_answer2:"reduce viteza, după care traversează intersecţia",
        image_url:null,
    },
    {
        question:"Conducătorul de autoturism care se află în spatele unui autobuz şi întâlneşte indicatorul „Oprire” trebuie:",
        answer:"să oprească şi să se asigure înainte de a traversa intersecţia, chiar dacă acest lucru a fost făcut şi de către conducătorul autobuzului",
        wrong_answer1:"să continue deplasarea şi să traverseze o dată cu autobuzul, deoarece conducătorul acestuia a oprit şi s-a asigurat",
        wrong_answer2:"să continue deplasarea şi să traverseze intersecţia imediat în urma autobuzului, deoarece, în acest caz, nu se expune niciunui pericol",
        image_url:null,
    },
    {
        question:"În intersecţii au prioritate de trecere vehiculele care întâlnesc unul dintre indicatoarele:",
        answer:"Intersecţie cu un drum fără prioritate",
        wrong_answer1:"Înainte",
        wrong_answer2:"Circulaţie în ambele sensuri",
        image_url:null,
    },
    {
        question:"La intersecţia nedirijată dintre un drum comunal şi unul local, prioritatea de trecere se acordă:",
        answer:"vehiculelor care circulă pe drumul comunal",
        wrong_answer1:"vehiculelor care circulă pe drumul local",
        wrong_answer2:"vehiculelor care vin din dreapta",
        image_url:null,
    },
    {
        question:"Care dintre conducătorii de vehicule, ce se apropie simultan de o intersecţie, are prioritate de trecere, în situaţia în care unul întâlneşte indicatorul Oprire, iar celălalt indicatorul Cedează trecerea?",
        answer:"conducătorul care circulă din dreapta",
        wrong_answer1:"conducătorul care întâlneşte indicatorul Cedează trecerea",
        wrong_answer2:"conducătorul care întâlneşte indicatorul Oprire",
        image_url:null,
    },
    {
        question:"La plecarea de pe loc cu autovehiculul, vă revin următoarele obligaţii",
        answer:"să acordaţi prioritate de trecere vehiculelor care circulă pe drum, indiferent de direcţia de mers",
        wrong_answer1:". să evitaţi ambalarea excesivă a motorului",
        wrong_answer2:"să evitaţi bruscarea comenzilor autovehiculului",
        image_url:null,
    },
    {
        question:"Cum procedează conducătorul de autovehicul care intenţionează să circule pe direcţia înainte printr-o intersecţie nedirijată?",
        answer:"reduce viteza şi acordă prioritate vehiculelor care vin din dreapta sa;",
        wrong_answer1:"reduce viteza şi acordă prioritate tuturor vehiculelor",
        wrong_answer2:"reduce viteza şi acordă prioritate vehiculelor care circulă din sens opus şi urmează să schimbe direcţia de mers spre stânga",
        image_url:null,
    },
    {
        question:"Cum procedaţi când circulaţi pe un drum public şi întâlniţi indicatorul „rioritate faţă de circulaţia din sens invers?",
        answer:"vă continuaţi deplasarea, pentru că aveţi prioritate de trecere;",
        wrong_answer1:"opriţi şi acordaţi prioritate de trecere vehiculelor care se apropie din sens opus;",
        wrong_answer2:"opriţi şi acordaţi prioritate numai vehiculelor cu gabarit depăşit, care se apropie din sens opus",
        image_url:null,
    },
    {
        question:". În ce situaţii sunteţi obligat să acordaţi prioritate de trecere?",
        answer:"într-o intersecţie nedirijată, atunci când pătrundeţi pe un drum naţional, venind de pe un drum judeţean",
        wrong_answer1:". la întâlnirea indicatorului Drum cu prioritate",
        wrong_answer2:"la întâlnirea pietonilor aflaţi pe sensul de mers opus",
        image_url:null,
    },
    {
        question:"Ce obligaţii aveţi dacă, circulând pe un drumul public cu mai multe benzi, banda pe care circulaţi se sfârşeşte şi trebuie să vă continuaţi deplasarea pe banda din stânga?",
        answer:"să permiteţi trecerea vehiculelor care circulă pe banda din stânga",
        wrong_answer1:"să semnalizaţi, pentru ca cei din spate să vă acorde prioritate",
        wrong_answer2:"să măriţi viteza, pentru a nu-i stânjeni pe ceilalţi participanţi la trafic",
        image_url:null,
    },
    {
        question:"Bicicliştii şi conducătorii de vehicule cu tracţiune animală sunt obligaţi să acorde întotdeauna prioritate?",
        answer:"nu, dacă semnalizarea rutieră nu prevede acest lucru",
        wrong_answer1:"da, deoarece viteza de deplasare este mică",
        wrong_answer2:"da, dacă circulă pe drumuri judeţene sau comunale",
        image_url:null,
    },
    {
        question:"Conducătorul unui vehicul este obligat să acorde prioritate de trecere într-o intersecţie nedirijată dacă:",
        answer:"pătrunde pe un drum naţional, venind de pe un drum judeţean, comunal sau local",
        wrong_answer1:"pătrunde pe un drum judeţean, venind de pe un drum naţional",
        wrong_answer2:"pătrunde pe un drum comunal sau local, venind de pe un drum judeţean",
        image_url:null,
    },
    {
        question:"La intersecţia nedirijată dintre un drum judeţean şi unul comunal sau local, prioritatea de trecere se acordă:",
        answer:"vehiculelor care circulă pe drumul judeţean",
        wrong_answer1:"vehiculelor care circulă pe drumul comunal sau local",
        wrong_answer2:"vehiculelor care vin din dreapta",
        image_url:null,
    },
    {
        question:"La ieşirea din zonele rezidenţiale sau pietonale, sunteţi obligat să acordaţi prioritate",
        answer:"tuturor vehiculelor cu care vă intersectaţi",
        wrong_answer1:"pietonilor de pe sensul opus de circulaţie",
        wrong_answer2:"autovehiculelor",
        image_url:null,
    },
    {
        question:"La intersecţia nedirijată dintre un drum naţional şi unul judeţean, comunal sau local, prioritatea de trecere se acordă:",
        answer:"vehiculelor care circulă pe drumul naţional",
        wrong_answer1:"vehiculelor care circulă pe drumul judeţean, comunal sau local",
        wrong_answer2:"vehiculelor care vin din dreapta",
        image_url:null,
    },
    {
        question:"Conducătorul de vehicul are obligaţia de a ceda trecerea la schimbarea direcţiei de mers spre stânga, în timp ce semnalul verde este în funcţiune? ",
        answer:"da, atât vehiculelor care circulă din sens opus, cât şi pietonilor care traversează strada pe care acesta urmează să intre, pe sensul său de mers",
        wrong_answer1:"nu, deoarece semnalul verde îi conferă prioritate de trecere",
        wrong_answer2:"nu, cu excepţia cazului în care, din sens opus, se apropie un mijloc de transport public",
        image_url:null,
    },
    {
        question:"Conducătorul auto care circulă pe banda de lângă acostament, în acelaşi sens cu autovehiculele din serviciile regulate de transport public de persoane, este obligat:",
        answer:"să permită conducătorilor acestor vehicule să efectueze manevrele necesare repunerii în mişcare din staţie, dacă este prevăzută cu alveolă ",
        wrong_answer1:"să nu depăşească un asemenea vehicul, când se află oprit în staţie",
        wrong_answer2:"să permită traversarea călătorilor pentru a se urca într-un asemenea vehicul",
        image_url:null,
    },
]