export const questions = [
    {
        question:"Viteza maximă cu care pot să conducă un autoturism, pe drumurile naţionale europene (E), persoanele care au mai puţin de un an de practică de conducere, este de:",
        answer:"80 km/h",
        wrong_answer1:"100 km/h",
        wrong_answer2:"90 km/h",
        image_url:null,
    },
    {
        question:"Într-o zonă rezidenţială puteţi circula cu",
        answer:"viteza maximă de 20 km/h",
        wrong_answer1:"viteza minimă obligatorie de 20 km/h",
        wrong_answer2:"viteza maximă de 30 km/h",
        image_url:null,
    },
    {
        question:"Care sunt vitezele maxime admise pentru categoria de autovehicule B?",
        answer:"130 km/h pe autostrăzi, 100 km/h pe drumurile expres sau naţionale europene şi 90 km/h pe celelalte categorii de drumuri",
        wrong_answer1:"90 km/h pe autostrăzi, 80 km/h pe drumurile expres sau naţionale europene şi 70 km/h pe celelalte categorii de drumuri",
        wrong_answer2:"130 km/h pe autostrăzi şi 90 km/h pe celelalte categorii de drumuri",
        image_url:null,
    },
    {
        question:"Viteza maximă cu care pot să conducă un autoturism, pe drumurile naţionale, altele decât cele europene (E), persoanele care au mai puţin de un an de practică de conducere, este de",
        answer:". 70 km/h",
        wrong_answer1:"90 km/h",
        wrong_answer2:"80 km/h",
        image_url:null,
    },
    {
        question:"Care este limita maximă de viteză în afara localităţilor, pe drumurile expres sau pe cele naţionale europene (E)?",
        answer:"100 km/h;",
        wrong_answer1:"110 km/h;",
        wrong_answer2:"90 km/h;",
        image_url:null,
    },
    {
        question:"Limita maximă de viteză pe care administratorul drumului public o poate stabili pe anumite sectoare, din interiorul localităţilor, pentru autovehiculele din categoriile A şi B, nu poate fi mai mare de:",
        answer:"80 km/h",
        wrong_answer1:"50 km/h",
        wrong_answer2:"110 km/h",
        image_url:null,
    },
    {
        question:"Care este limita legală de viteză în afara localităţilor, pe celelalte categorii de drumuri, altele decât autostrăzile, drumurile expres sau cele naţionale europene (E)?",
        answer:"90 km/h;",
        wrong_answer1:"70 km/h",
        wrong_answer2:"100 km/h",
        image_url:null,
    },
    {
        question:"Conduceţi un autoturism care tractează o semiremorcă pe un drum naţional european (E). Care este viteza maximă cu care aveţi voie să circulaţi în afara localităţilor? ",
        answer:"90 km/h",
        wrong_answer1:"100 km/h",
        wrong_answer2:"70 km/h",
        image_url:null,
    },
    {
        question:"Limita inferioară de viteză pe care administratorul drumului public o poate stabili pe anumite sectoare, din interiorul localităţilor, nu poate fi mai mică de",
        answer:"10 km/h pentru tramvaie şi 30 km/h pentru toate autovehiculele",
        wrong_answer1:". 20 km/h pentru tramvaie şi 40 km/h pentru toate autovehiculele",
        wrong_answer2:"30 km/h pentru tramvaie şi 50 km/h pentru toate autovehiculele",
        image_url:null,
    },
    {
        question:"La o intersecţie semaforizată, semnalul verde se schimbă în galben. Conducătorul unui autovehiculul, fiind foarte aproape de semafor, opreşte brusc şi este lovit din spate de conducătorul care îl urma. Care dintre cei doi conducători a greşit?",
        answer:"conducătorul autovehiculului din spate, care nu a păstrat distanţa de siguranţă în mers;",
        wrong_answer1:"conducătorul primului autovehicul, care a oprit brusc",
        wrong_answer2:"ambii conducãtori",
        image_url:null,
    },
    {
        question:"Cum trebuie să procedaţi atunci când, circulând pe drumul naţional într-o localitate rurală, treceţi pe lângă o coloană militară care se deplasează în aceeaşi direcţie?",
        answer:"reduceţi viteza până la limitele prevăzute de lege, dacă drumul are o singură bandă pe sens",
        wrong_answer1:"măriţi viteza şi depăşiţi coloana",
        wrong_answer2:"folosiţi avertizorul sonor de la minimum 150 m",
        image_url:null,
    },
    {
        question:"Cu ce viteză veţi efectua virajul spre stânga într-o intersecţie nedirijată?",
        answer:"cu o viteză care să nu depăşească 30 km/h în localităţi sau 50 km/h în afara localităţilor",
        wrong_answer1:"cu o viteză mai mare decât cea legală",
        wrong_answer2:"cu o viteză de cel mult 80 km/h;",
        image_url:null,
    },
    {
        question:"Cu ce viteză maximă pot circula autovehiculele din categoriile A şi B pe autostradă când vizibilitatea este mai mică de 100m din cauza fumului de la un câmp pe care ard resturi vegetale?",
        answer:"50 km/h cel mult;",
        wrong_answer1:"110 km/h",
        wrong_answer2:"130 km/h",
        image_url:null,
    },
    {
        question:"Care este viteza maximă într-o zonă pietonală ?",
        answer:"5km/h;",
        wrong_answer1:"25km/h ",
        wrong_answer2:"15km/h ",
        image_url:null,
    },
    {
        question:"Care dintre situaţiile de mai jos vă impun reducerea vitezei ?",
        answer:"balansarea în plan vertical a braţului poliţistului rutier",
        wrong_answer1:"balansarea în plan vertical a braţului biciclistului aflat în trafic",
        wrong_answer2:"balansarea în plan vertical a braţului conducătorului de animale pe drumul public",
        image_url:null,
    },
    {
        question:"Cu ce viteză veţi putea rula dacă sunteţi la volan?",
        answer:"50 km/h",
        wrong_answer1:"60 km/h",
        wrong_answer2:"40 km/h",
        image_url:"https://i.imgur.com/c7AAkjk.png",
    },
    {
        question:"În situaţia dată",
        answer:"veţi circula cu maximum 30 km/h pe sectorul de drum denivelat",
        wrong_answer1:"veţi circula cu prudenţă până la prima intersecţie",
        wrong_answer2:"veţi circula cu minimum 30 km/h",
        image_url:"https://i.imgur.com/57rCkjB.png",
    },
    {
        question:"Conducătorul autoturismului din imagine va circulacu:",
        answer:"80 km/h",
        wrong_answer1:"90 km/h",
        wrong_answer2:"100 km/h",
        image_url:"https://i.imgur.com/xBt2EyF.png",
    },
    {
        question:"Dacă vreţi să părăsiţi autostrada:",
        answer:"reduceţi viteza",
        wrong_answer1:"măriţi viteza",
        wrong_answer2:"circulaţi cu aceeaşi viteză",
        image_url:"https://i.imgur.com/eU40Ipx.png",
    },
    {
        question:"După o ploaie torenţială, este necesar să se păstreze o distanţă considerabil mai mare faţă de vehiculul care circulă în faţă?",
        answer:"da, întrucât spaţiul de frânare se măreşte",
        wrong_answer1:"nu, întrucât acest lucru duce la aglomerarea traficului",
        wrong_answer2:"da, deoarece nu se observă indicatoarele",
        image_url:"https://i.imgur.com/pD5oMtL.png",
    },
]