export const questions = [
    {
        question:"Unde trebuie să declaraţi pierderea, furtul sau distrugerea permisului de conducere:",
        answer:"la unitatea emitentă",
        wrong_answer1:"la poliţia de care aparţineţi cu domiciliul",
        wrong_answer2:"la cea mai apropiată secţie de poliţie",
        image_url:null,
    },
    {
        question:"Permisul de conducere categoria B este valabil şi pentru conducerea unui autovehicul destinat transportului de persoane, având mai mult de 8 locuri pe scaune, în afara locului conducptorului?",
        answer:"nu",
        wrong_answer1:"da, dacă posesorul permisului are o vechime în conducere de cel puţin 1 an",
        wrong_answer2:"da, dacă conducătorul posedă şi categoria BE a permisului de conducere.",
        image_url:null,
    },
    {
        question:"Precizaţi dacă posesorul unui permis de conducere categoria B are permisiunea de a conduce un autoturism cu remorcă:",
        answer:"da, dacă masa remorcii nu depăşeşte 750 kg",
        wrong_answer1:"da, cu condiţia ca acesta să aibă permis de cel puţin 3 ani",
        wrong_answer2:"nu, deoarece pentru o astfel de remorcă este necesar un permis de conducere categoria BE ",
        image_url:null,
    },
    {
        question:"Care dintre următoarele fapte constituie infracţiuni?",
        answer:"conducerea sub influenţa unor produse sau substanţe stupefiante sau a unor medicamente cu efecte similare ",
        wrong_answer1:"nerespectarea semnalelor poliţiştilor la trecerea coloanelor oficiale",
        wrong_answer2:"depăşirea limitei legale de viteză cu peste 50 km/h",
        image_url:null,
    },
    {
        question:"Care dintre faptele de mai jos se consideră infracţiune şi se pedepseşte ca atare?",
        answer:"repararea autovehicului ce prezintă urme de accident, fără autorizaţia poliţiei",
        wrong_answer1:"sustragerea de la obligaţia de a supune autovehiculul inspecţiei tehnice periodice",
        wrong_answer2:"părăsirea locului accidentului care a avut ca urmare avarii",
        image_url:null,
    },
    {
        question:"În care dintre situaţiile de mai jos se anulează permisul de conducere?",
        answer:"pentru infracţiunile care s-au soldat cu moartea sau vătămarea gravă a unei persoane, săvârşite ca urmare a nerespectării regulilor de circulaţie",
        wrong_answer1:"pentru conducerea unui autovehicul sub influenţa băuturilor alcoolice",
        wrong_answer2:"pentru nerespectarea semnalelor poliţiştilor la trecerea coloanelor oficiale",
        image_url:null,
    },
    {
        question:"Care dintre faptele de mai jos atrag suspendarea exercitării dreptului de conduce pe o perioadă de 90 de zile?",
        answer:"conducerea sub influenţa băuturilor alcoolice",
        wrong_answer1:"conducerea sub influenţa produselor stupefiante",
        wrong_answer2:"conducerea unui vehicul neînmatriculat",
        image_url:null,
    },
    {
        question:"Conducerea pe drumul public a autovehicului de către o persoană cu o alcoolemie în sânge de peste 0,8 g/l atrage ",
        answer:"răspunderea penală şi anularea permisului de conducere",
        wrong_answer1:"răspunderea contravenţională şi reţinerea permisului de conducere",
        wrong_answer2:"răspunderea penală şi suspendarea exercitării dreptului de a conduce pe o perioadă de 90 de zile",
        image_url:null,
    },
    {
        question:"Sustragerea de la recoltarea probelor biologice, în vederea stabilirii alcoolemiei, constituie",
        answer:"infracţiune, şi atrage anularea permisului de conducere",
        wrong_answer1:"contravenţie, şi se pedepseşte cu închisoare",
        wrong_answer2:"contravenţie, şi atrage reţinerea permisului de conducere",
        image_url:null,
    },
    {
        question:"Cum se pedepseşte conducerea pe drumurile publice a unui autovehicul din categoria C, de către o persoană al cărei permis este valabil pentru categoria B?",
        answer:"penal",
        wrong_answer1:"contravenţional",
        wrong_answer2:"amendă contravenţională şi reţinerea permisului de conducere",
        image_url:null,
    },
    {
        question:"Sunteţi obligat să vă supuneţi recoltării probelor biologice, în cazul unui accident de circulaţie din care a rezultat moartea sau vătămarea integrităţii corporale ori a sănătăţii unor persoane?",
        answer:"da",
        wrong_answer1:"da, dar numai dacă sunteţi vinovat de producerea accidentului",
        wrong_answer2:"nu, dacă aţi fost testat cu un aparat autoriz",
        image_url:null,
    },
    {
        question:"Încredinţarea cu ştiinţă a unui autovehicul, pentru a fi condus pe drumul public, unei persoane care nu posedă permis de conducere se pedepseşte:",
        answer:"penal",
        wrong_answer1:"contravenţional",
        wrong_answer2:"cu amendă contravenţională şi anularea permisului de conducere",
        image_url:null,
    },
    {
        question:"Distrugerea, degradarea sau aducerea în stare de neîntrebuinţare, în mod intenţionat, a indicatoarelor, semafoarelor, amenajărilor rutiere se pedepseşte astfel:",
        answer:"penal;",
        wrong_answer1:"cu amendă contravenţională şi puncte de penalizar",
        wrong_answer2:"cu suspendarea exercitării dreptului de a conduce autovehicule",
        image_url:null,
    },
    {
        question:"Conduceţi autovehiculul pe drumurile publice şi refuzaţi recoltarea unor probe biologice în vederea stabilirii alcoolemiei. Veţi fi pedepsit penal? ",
        answer:"da;",
        wrong_answer1:"numai dacă sunteţi implicat într-un accident de circulaţie",
        wrong_answer2:"nu",
        image_url:null,
    },
    {
        question:"Care este valoarea alcoolemiei în sânge peste care se aplică pedeapsa penală pentru un conducător aflat la volan?",
        answer:"0,8 g/l",
        wrong_answer1:"0,5 g/l",
        wrong_answer2:"1 g/l",
        image_url:null,
    },
    {
        question:"Conducătorul unui autovehicul angajat într-un accident din care a rezultat moartea sau rănirea unei persoane poate părăsi locul faptei fără încuviinţarea poliţiei?",
        answer:"nu, întrucât fapta constituie infracţiune",
        wrong_answer1:"da, dacă accidentul nu s-a produs din vina sa",
        wrong_answer2:"da, dacă autovehiculul a blocat circulaţia",
        image_url:null,
    },
    {
        question:"Precizaţi măsura care se ia atunci când titularul permisului de conducere a fost declarat inapt pentru a conduce autovehicule, de către o instituţie medicală autorizată",
        answer:". i se retrage permisul de conducere",
        wrong_answer1:"i se aplică sancţiunile contravenţionale complementare",
        wrong_answer2:"va fi reexaminat de către autoritatea competentă",
        image_url:null,
    },
    {
        question:"În care dintre următoarele situaţii se anulează permisul de conducere?",
        answer:"în urma unei condamnări, printr-o hotărâre definitivă, pentru o infracţiune la regimul circulaţiei",
        wrong_answer1:"pentru încălcarea dispoziţiilor legale referitoare la folosirea luminilor de întâlnire pe timp de noapte, în afara localităţilor",
        wrong_answer2:"pentru încălcarea dispoziţiilor legale referitoare la obligaţia de a semnaliza schimbarea direcţiei de mers.",
        image_url:null,
    }
]